.open job_map.db;

CREATE TABLE IF NOT EXISTS `users` (
    `id` INTEGER,
    `user_pictures` TEXT NOT NULL UNIQUE DEFAULT '/job-map-resources/media/pictures/user-pictures/default.jpg',
    `user_pictures_number` INTEGER NOT NULL DEFAULT 1,
    `user_videos_number` INTEGER NOT NULL DEFAULT 0,
    `user_audios_number` INTEGER NOT NULL DEFAULT 0,
    `username` TEXT NOT NULL UNIQUE DEFAULT 'anonymous',
    `email_address` TEXT NOT NULL UNIQUE DEFAULT 'anonymous@email.com',
    `password` TEXT NOT NULL DEFAULT 'secret',
    `hash_key` TEXT NOT NULL DEFAULT 'qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopas',
    `name` TEXT NOT NULL DEFAULT 'Unknown Name',
    `born_place` TEXT NOT NULL DEFAULT 'Unknown Place',
    `birthday` TEXT NOT NULL DEFAULT '1970-01-01',
    `home_address` TEXT NOT NULL DEFAULT 'Unknown Address',
    `living_address` TEXT NOT NULL DEFAULT 'Unknown Address',
    `phone_number` TEXT NOT NULL DEFAULT '+62 845-3783-2897',
    'social_media_account_links' TEXT NOT NULL DEFAULT '["None"]',
    `website_address` TEXT NOT NULL DEFAULT 'http://www.unknown.website.address.com',
    `gender` TEXT CHECK(`gender` in ('Male', 'Female')) NOT NULL DEFAULT 'Male',
    `status` TEXT CHECK(`status` in ('Single', 'Married', 'Widow', 'Widower')) NOT NULL DEFAULT 'Single',
    `height_in_cm` INTEGER NOT NULL DEFAULT 150,
    `weight_in_kg` INTEGER NOT NULL DEFAULT 40,
    `nationality` TEXT NOT NULL DEFAULT 'Unknown Nationality',
    `languages` TEXT NOT NULL DEFAULT '["None"]',
    `religion` TEXT CHECK(`religion` in ('Islam', 'Protestanism', 'Catholic', 'Hindu', 'Buddha', 'Konghucu')) NOT NULL DEFAULT 'Islam',
    `formal_education` TEXT NOT NULL DEFAULT '["None"]',
    `not_formal_education` TEXT NOT NULL DEFAULT '["None"]',
    `hobbies` TEXT NOT NULL DEFAULT '["None"]',
    `specialities` TEXT NOT NULL DEFAULT '["None"]',
    `work_experiences` TEXT NOT NULL DEFAULT '["None"]',
    `organization_history` TEXT NOT NULL DEFAULT '["None"]',
    `certifications` TEXT NOT NULL DEFAULT '["None"]',
    `achievements` TEXT NOT NULL DEFAULT '["None"]',
    `created_date` TEXT NOT NULL DEFAULT '1970-01-01',
    `created_time` TEXT NOT NULL DEFAULT '00:00:00',
    `updated_date` TEXT NOT NULL DEFAULT '1970-01-01',
    `updated_time` TEXT NOT NULL DEFAULT '00:00:00',
    PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `companies` (
    `id` INTEGER,
    `company_logo` TEXT NOT NULL UNIQUE DEFAULT '/job-map-resources/media/pictures/company-logos/default.jpg',
    `company_pictures_number` INTEGER NOT NULL DEFAULT 1,
    `company_videos_number` INTEGER NOT NULL DEFAULT 0,
    `company_audios_number` INTEGER NOT NULL DEFAULT 0,
    `name` TEXT NOT NULL DEFAULT 'Unknown Company',
    `birthday` TEXT NOT NULL DEFAULT '1970-01-01',
    `address` TEXT NOT NULL DEFAULT 'Unknown Address',
    `phone_number` TEXT NOT NULL DEFAULT '+62 845-3783-2897',
    `email_address` TEXT NOT NULL DEFAULT 'unknown.company@email.com',
    `social_media_account_links` TEXT NOT NULL DEFAULT '["None"]',
    `website_address` TEXT NOT NULL DEFAULT 'http://www.unknown.website.address.com',
    `introduction` TEXT NOT NULL DEFAULT 'None',
    `visions` TEXT NOT NULL DEFAULT '["None"]',
    `missions` TEXT NOT NULL DEFAULT '["None"]',
    `policy` TEXT NOT NULL DEFAULT '["None"]',
    `product_or_service_description` TEXT NOT NULL DEFAULT 'None',
    `portofolio` TEXT NOT NULL DEFAULT 'None',
    `unique_identity` TEXT NOT NULL DEFAULT 'None',
    `certifications` TEXT NOT NULL DEFAULT '["None"]',
    `achievements` TEXT NOT NULL DEFAULT '["None"]',
    `company_owner_id` INTEGER NOT NULL DEFAULT 0,
    `created_date` TEXT NOT NULL DEFAULT '1970-01-01',
    `created_time` TEXT NOT NULL DEFAULT '00:00:00',
    `updated_date` TEXT NOT NULL DEFAULT '1970-01-01',
    `updated_time` TEXT NOT NULL DEFAULT '00:00:00',
    PRIMARY KEY(`id`),
    FOREIGN KEY(`company_owner_id`) REFERENCES `users`(`id`)
);

CREATE TABLE IF NOT EXISTS `job_vacancies` (
    `id` INTEGER,
    `status` TEXT CHECK(`status` IN ('Pending', 'Accepted', 'Rejected', 'Cancelled')) DEFAULT 'Pending',
    `job_type` TEXT NOT NULL DEFAULT 'Unknown Job Type',
    `location` TEXT NOT NULL DEFAULT 'Unknown Place',
    `title` TEXT NOT NULL DEFAULT 'Untitled',
    `description` TEXT NOT NULL DEFAULT 'None',
    `tags` TEXT NOT NULL DEFAULT '["None"]',
    `company_id` INTEGER NOT NULL DEFAULT 0,
    `created_date` TEXT NOT NULL DEFAULT '1970-01-01',
    `created_time` TEXT NOT NULL DEFAULT '00:00:00',
    `updated_date` TEXT NOT NULL DEFAULT '1970-01-01',
    `updated_time` TEXT NOT NULL DEFAULT '00:00:00',
    PRIMARY KEY(`id`),
    FOREIGN KEY(`company_id`) REFERENCES `companies`(`id`)
);

CREATE TABLE IF NOT EXISTS `job_requests` (
    `status` TEXT CHECK(`status` IN ('Pending', 'Accepted', 'Rejected', 'Cancelled')) DEFAULT 'Pending',
    `job_type` TEXT NOT NULL DEFAULT 'Unknown Job Type',
    `location` TEXT NOT NULL DEFAULT 'Unknown Place',
    `title` TEXT NOT NULL DEFAULT 'Untitled',
    `message` TEXT NOT NULL DEFAULT 'None',
    `company_id` INTEGER NOT NULL DEFAULT 0,
    `receiver_id` INTEGER NOT NULL DEFAULT 0,
    `created_date` TEXT NOT NULL DEFAULT '1970-01-01',
    `created_time` TEXT NOT NULL DEFAULT '00:00:00',
    `updated_date` TEXT NOT NULL DEFAULT '1970-01-01',
    `updated_time` TEXT NOT NULL DEFAULT '00:00:00',
    FOREIGN KEY(`company_id`) REFERENCES `companies`(`id`),
    FOREIGN KEY(`receiver_id`) REFERENCES `users`(`id`)
);


CREATE TABLE IF NOT EXISTS `job_submissions` (
    `status` TEXT CHECK(`status` IN ('Pending', 'Accepted', 'Rejected', 'Cancelled')) DEFAULT 'Pending',
    `sender_id` INTEGER NOT NULL DEFAULT 0,
    `job_vacancy_id` INTEGER NOT NULL DEFAULT 0,
    `created_date` TEXT NOT NULL DEFAULT '1970-01-01',
    `created_time` TEXT NOT NULL DEFAULT '00:00:00',
    FOREIGN KEY(`sender_id`) REFERENCES `users`(`id`),
    FOREIGN KEY(`job_vacancy_id`) REFERENCES `job_vacancies`(`id`)

);

INSERT INTO `users` VALUES(
    NULL,
    '/job-map/application/views/media/pictures/user-pictures/1/1.jpg',
    1,
    0,
    0,
    'a-naive-dreamer',
    'anaivedreamer@gmail.com',
    'secret',
    'qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopaa',
    'Atallabela Yosua',
    'Palangka Raya',
    '2001-06-09',
    'Tampung Penyang I Street',
    'Teluk Banyubiru Street',
    '+62 845-3726-2723',
    '["https://github.com/a-naive-dreamer"]',
    'https://justanaivedreamer.wordpress.com',
    'Male',
    'Single',
    176,
    41,
    'Indonesia',
    '["Indonesia", "Dayak Ngaju", "Banjar"]',
    'Protestanism',
    '["SD Negeri 6 Langkai", "SMP Negeri 8 Palangka Raya", "SMK Negeri 1 Palangka Raya"]',
    DEFAULT,
    '["Badminton", "Coding", "Photography", "Drawing", "Watch Animes"]',
    '["Kill"]',
    '["VEDC BOE Malang"]',
    '["PHP Malang User Group"]',
    DEFAULT,
    DEFAULT,
    CURRENT_DATE,
    CURRENT_TIME,
    CURRENT_DATE,
    CURRENT_TIME
), (
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT
);

INSERT INTO `companies` VALUES(
    1,
    '/job-map/application/views/media/pictures/company-logos/1/1.jpg',
    1,
    0,
    0,
    'Tampung Penyang Software House',
    '2018-09-18',
    'Tampung Penyang V Street',
    '+62 839-3833-3732',
    'tampung_penyang@software_house.com',
    '["https://fake-link.com/fake-account"]',
    'https://tampungpenyangsofwarehouse.wordpress.com',
    'Just Fake Company.',
    '["Conquer IT world.", "Conquer Atlantic Ocean.", "Another?"]',
    '["Buy more and more supercomputer.", "Add more and more RAM Capacity.", "Anything?"]',
    '["Consumers is Kings.", "Employers is Buttlers.", "Don&apos;t add more from this!"]',
    'Nothing.',
    'Come on, we are developing company.',
    'Nothing again.',
    '["And nothing again."]',
    '["NOTHING."]',
    1,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT
), (
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    CURRENT_DATE,
    CURRENT_TIME,
    CURRENT_DATE,
    CURRENT_TIME
);

INSERT INTO `job_vacancies` VALUES(
    NULL,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    1,
    CURRENT_DATE,
    CURRENT_TIME,
    CURRENT_DATE,
    CURRENT_TIME
);

INSERT INTO `job_requests` VALUES(
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    1,
    1,
    CURRENT_DATE,
    CURRENT_TIME,
    CURRENT_DATE,
    CURRENT_TIME
);

INSERT INTO `job_submissions` VALUES(
    DEFAULT,
    1,
    1,
    CURRENT_DATE,
    CURRENT_TIME
);
