.open job_map.db;

CREATE TABLE IF NOT EXISTS `users` (
    `id` INTEGER CHECK(LENGTH(`id`) <= 5 AND LENGTH(`id`) >= 0),
    `user_pictures` TEXT CHECK(LENGTH(`user_pictures`) <= 75) NOT NULL UNIQUE DEFAULT '/job-map-resources/media/pictures/user-pictures/default.jpg',
    `user_pictures_number` INTEGER CHECK(LENGTH(`user_pictures_number`) <= 5 AND LENGTH(`user_pictures_number`) >= 0) NOT NULL DEFAULT 1,
    `user_videos_number` INTEGER CHECK(LENGTH(`user_videos_number`) <= 5 AND LENGTH(`user_videos_number`) >= 0) NOT NULL DEFAULT 0,
    `user_audios_number` INTEGER CHECK(LENGTH(`user_audios_number`) <= 5 AND LENGTH(`user_audios_number`) >= 0) NOT NULL DEFAULT 0,
    `username` TEXT CHECK(LENGTH(`username`) <= 50) NOT NULL UNIQUE DEFAULT 'anonymous',
    `email_address` TEXT CHECK(LENGTH(`email_address`) <= 50) NOT NULL UNIQUE DEFAULT 'anonymous@email.com',
    `password` TEXT CHECK(LENGTH(`password`) <= 64) NOT NULL DEFAULT 'secret',
    `hash_key` TEXT CHECK(LENGTH(`hash_key`) <= 64) NOT NULL DEFAULT 'qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopas',
    `name` TEXT CHECK(LENGTH(`name`) <= 50) NOT NULL DEFAULT 'Unknown Name',
    `born_place` TEXT CHECK(LENGTH(`born_place`) <= 50) NOT NULL DEFAULT 'Unknown Place',
    `birthday` TEXT CHECK(`birthday` LIKE '____-__-__') NOT NULL DEFAULT '1970-01-01',
    `home_address` TEXT CHECK(LENGTH(`home_address`) <= 50) NOT NULL DEFAULT 'Unknown Address',
    `living_address` TEXT CHECK(LENGTH(`living_address`) <= 50) NOT NULL DEFAULT 'Unknown Address',
    `phone_number` TEXT CHECK(LENGTH(`phone_number`) <= 21) NOT NULL DEFAULT '+62 845-3783-2897',
    `social_media_account_links` TEXT CHECK(LENGTH(`social_media_account_links`) <= 255) NOT NULL DEFAULT '["None"]',
    `website_address` TEXT CHECK(LENGTH(`website_address`) <= 50) NOT NULL DEFAULT 'http://www.unknown.website.address.com',
    `gender` TEXT CHECK(`gender` in ('Male', 'Female')) NOT NULL DEFAULT 'Male',
    `status` TEXT CHECK(`status` in ('Single', 'Married', 'Widow', 'Widower')) NOT NULL DEFAULT 'Single',
    `height_in_cm` INTEGER CHECK(`height_in_cm` <= 200 AND `height_in_cm` >= 150) NOT NULL DEFAULT 150,
    `weight_in_kg` INTEGER CHECK(`weight_in_kg` <= 100 AND `weight_in_kg` >= 40) NOT NULL DEFAULT 40,
    `nationality` TEXT CHECK(LENGTH(`nationality`) <= 50) NOT NULL DEFAULT 'Unknown Nationality',
    `languages` TEXT CHECK(LENGTH(`languages`) <= 255) NOT NULL DEFAULT '["None"]',
    `religion` TEXT CHECK(`religion` in ('Islam', 'Protestanism', 'Catholic', 'Hindu', 'Buddha', 'Konghucu')) NOT NULL DEFAULT 'Islam',
    `formal_education` TEXT CHECK(LENGTH(`formal_education`) <= 255) NOT NULL DEFAULT '["None"]',
    `not_formal_education` TEXT CHECK(LENGTH(`not_formal_education`) <= 255) NOT NULL DEFAULT '["None"]',
    `hobbies` TEXT CHECK(LENGTH(`hobbies`) <= 255) NOT NULL DEFAULT '["None"]',
    `specialities` TEXT CHECK(LENGTH(`specialities`) <= 255) NOT NULL DEFAULT '["None"]',
    `work_experiences` TEXT CHECK(LENGTH(`work_experiences`) <= 255) NOT NULL DEFAULT '["None"]',
    `organization_history` TEXT CHECK(LENGTH(`organization_history`) <= 255) NOT NULL DEFAULT '["None"]',
    `certifications` TEXT CHECK(LENGTH(`certifications`) <= 255) NOT NULL DEFAULT '["None"]',
    `achievements` TEXT CHECK(LENGTH(`achievements`) <= 255) NOT NULL DEFAULT '["None"]',
    `created_date` TEXT CHECK(`created_date` LIKE '____-__-__') NOT NULL DEFAULT '1970-01-01',
    `created_time` TEXT CHECK(`created_time` <= '__:__:__') NOT NULL DEFAULT '00:00:00',
    `updated_date` TEXT CHECK(`updated_date` LIKE '____-__-__') NOT NULL DEFAULT '1970-01-01',
    `updated_time` TEXT CHECK(`updated_time` <= '__:__:__') NOT NULL DEFAULT '00:00:00',
    PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `companies` (
    `id` INTEGER CHECK(LENGTH(`id`) <= 5 AND LENGTH(`id`) >= 0),
    `company_logo` TEXT CHECK(LENGTH(`company_logo`) <= ) NOT NULL UNIQUE DEFAULT '/job-map-resources/media/pictures/company-logos/default.jpg',
    `company_pictures_number` INTEGER CHECK(LENGTH() <= ) NOT NULL DEFAULT 1,
    `company_videos_number` INTEGER CHECK(LENGTH() <= ) NOT NULL DEFAULT 0,
    `company_audios_number` INTEGER CHECK(LENGTH() <= ) NOT NULL DEFAULT 0,
    `name` TEXT CHECK(LENGTH(`name`) <= ) NOT NULL DEFAULT 'Unknown Company',
    `birthday` TEXT CHECK(`birthday` LIKE '____-__-__') NOT NULL DEFAULT '1970-01-01',
    `address` TEXT CHECK(LENGTH(`address`) <= 50) NOT NULL DEFAULT 'Unknown Address',
    `phone_number` TEXT CHECK(LENGTH(`phone_number`) <= 21) NOT NULL DEFAULT '+62 845-3783-2897',
    `email_address` TEXT CHECK(LENGTH(`email_address`) <= 50) NOT NULL DEFAULT 'unknown.company@email.com',
    `social_media_account_links` TEXT CHECK(LENGTH(`social_media_account_links`) <= 255) NOT NULL DEFAULT '["None"]',
    `website_address` TEXT CHECK(LENGTH(`website_address`) <= 50) NOT NULL DEFAULT 'http://www.unknown.website.address.com',
    `introduction` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT 'None',
    `visions` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT '["None"]',
    `missions` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT '["None"]',
    `policy` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT '["None"]',
    `product_or_service_description` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT 'None',
    `portofolio` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT 'None',
    `unique_identity` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT 'None',
    `certifications` TEXT CHECK(LENGTH(`certifications`) <= 255) NOT NULL DEFAULT '["None"]',
    `achievements` TEXT CHECK(LENGTH(`achievements`) <= 255) NOT NULL DEFAULT '["None"]',
    `company_owner_id` INTEGER CHECK(LENGTH(`company_owner_id`) <= 5 AND LENGTH(`company_owner_id`) >= 0) NOT NULL DEFAULT 0,
    `created_date` TEXT CHECK(`created_date` LIKE '____-__-__') NOT NULL DEFAULT '1970-01-01',
    `created_time` TEXT CHECK(`created_time` <= '__:__:__') NOT NULL DEFAULT '00:00:00',
    `updated_date` TEXT CHECK(`updated_date` LIKE '____-__-__') NOT NULL DEFAULT '1970-01-01',
    `updated_time` TEXT CHECK(`updated_time` <= '__:__:__') NOT NULL DEFAULT '00:00:00',
    PRIMARY KEY(`id`),
    FOREIGN KEY(`company_owner_id`) REFERENCES `users`(`id`)
);

CREATE TABLE IF NOT EXISTS `job_vacancies` (
    `id` INTEGER CHECK(LENGTH(`id`) <= 5 AND LENGTH(`id`) >= 0),
    `status` TEXT CHECK(`status` IN ('Pending', 'Accepted', 'Rejected', 'Cancelled')) DEFAULT 'Pending',
    `job_type` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT 'Unknown Job Type',
    `location` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT 'Unknown Place',
    `title` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT 'Untitled',
    `description` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT 'None',
    `tags` TEXT CHECK(LENGTH() <= 255) NOT NULL DEFAULT '["None"]',
    `company_owner_id` INTEGER CHECK(LENGTH(`company_owner_id`) <= 5 AND LENGTH(`company_owner_id`) >= 0) NOT NULL DEFAULT 0,
    `created_date` TEXT CHECK(`created_date` LIKE '____-__-__') NOT NULL DEFAULT '1970-01-01',
    `created_time` TEXT CHECK(`created_time` <= '__:__:__') NOT NULL DEFAULT '00:00:00',
    `updated_date` TEXT CHECK(`updated_date` LIKE '____-__-__') NOT NULL DEFAULT '1970-01-01',
    `updated_time` TEXT CHECK(`updated_time` <= '__:__:__') NOT NULL DEFAULT '00:00:00',
    PRIMARY KEY(`id`),
    FOREIGN KEY(`company_id`) REFERENCES `companies`(`id`)
);

CREATE TABLE IF NOT EXISTS `job_requests` (
    `status` TEXT CHECK(`status` IN ('Pending', 'Accepted', 'Rejected', 'Cancelled')) DEFAULT 'Pending',
    `job_type` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT 'Unknown Job Type',
    `location` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT 'Unknown Place',
    `title` TEXT CHECK(LENGTH() <= ) NOT NULL DEFAULT 'Untitled',
    `message` TEXT CHECK(LENGTH() <= 255) NOT NULL DEFAULT 'None',
    `company_id` INTEGER CHECK(LENGTH(`company_id`) <= 5 AND LENGTH(`company_id`) >= 0) NOT NULL DEFAULT 0,
    `receiver_id` INTEGER CHECK(LENGTH(`receiver_id`) <= 5 AND LENGTH(`receiver_id`) >= 0) NOT NULL DEFAULT 0,
    `created_date` TEXT CHECK(`created_date` LIKE '____-__-__') NOT NULL DEFAULT '1970-01-01',
    `created_time` TEXT CHECK(`created_time` <= '__:__:__') NOT NULL DEFAULT '00:00:00',
    `updated_date` TEXT CHECK(`updated_date` LIKE '____-__-__') NOT NULL DEFAULT '1970-01-01',
    `updated_time` TEXT CHECK(`updated_time` <= '__:__:__') NOT NULL DEFAULT '00:00:00',
    FOREIGN KEY(`company_id`) REFERENCES `companies`(`id`),
    FOREIGN KEY(`receiver_id`) REFERENCES `users`(`id`)
);


CREATE TABLE IF NOT EXISTS `job_submissions` (
    `status` TEXT CHECK(`status` IN ('Pending', 'Accepted', 'Rejected', 'Cancelled')) DEFAULT 'Pending',
    `sender_id` INTEGER CHECK(LENGTH(`sender_id`) <= 5 AND LENGTH(`sender_id`) >= 0) NOT NULL DEFAULT 0,
    `job_vacancy_id` INTEGER CHECK(LENGTH(`job_vacancy_id`) <= 5 AND LENGTH(`job_vacancy_id`) >= 0) NOT NULL DEFAULT 0,
    `created_date` TEXT CHECK(`created_date` LIKE '____-__-__') NOT NULL DEFAULT '1970-01-01',
    `created_time` TEXT CHECK(`created_time` <= '__:__:__') NOT NULL DEFAULT '00:00:00',
    FOREIGN KEY(`sender_id`) REFERENCES `users`(`id`),
    FOREIGN KEY(`job_vacancy_id`) REFERENCES `job_vacancies`(`id`)

);

INSERT INTO `users` VALUES(
    NULL,
    '/job-map/application/views/media/pictures/user-pictures/1/1.jpg',
    1,
    0,
    0,
    'a-naive-dreamer',
    'anaivedreamer@gmail.com',
    'secret',
    'qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopaa',
    'Atallabela Yosua',
    'Palangka Raya',
    '2001-06-09',
    'Tampung Penyang I Street',
    'Teluk Banyubiru Street',
    '+62 845-3726-2723',
    '["https://github.com/a-naive-dreamer"]',
    'https://justanaivedreamer.wordpress.com',
    'Male',
    'Single',
    176,
    41,
    'Indonesia',
    '["Indonesia", "Dayak Ngaju", "Banjar"]',
    'Protestanism',
    '["SD Negeri 6 Langkai", "SMP Negeri 8 Palangka Raya", "SMK Negeri 1 Palangka Raya"]',
    '["None"]',
    '["Badminton", "Coding", "Photography", "Drawing", "Watch Animes"]',
    '["Kill"]',
    '["VEDC BOE Malang"]',
    '["PHP Malang User Group"]',
    '["None"]',
    '["None"]',
    CURRENT_DATE,
    CURRENT_TIME,
    CURRENT_DATE,
    CURRENT_TIME
), (
    0,
    '/job-map-resources/media/pictures/user-pictures/default.jpg',
    1,
    0,
    0,
    'anonymous',
    'anonymous@email.com',
    'secret',
    'qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopas',
    'Unknown Name',
    'Unknown Place',
    '1970-01-01',
    'Unknown Address',
    'Unknown Address',
    '+62 845-3783-2897',
    '["None"]',
    'http://www.unknown.website.address.com',
    'Male',
    'Single',
    150,
    40,
    'Unknown Nationality',
    '["None"]',
    'Islam',
    '["None"]',
    '["None"]',
    '["None"]',
    '["None"]',
    '["None"]',
    '["None"]',
    '["None"]',
    '["None"]',
    '1970-01-01',
    '00:00:00',
    '1970-01-01',
    '00:00:00'
);

INSERT INTO `companies` VALUES(
    1,
    '/job-map/application/views/media/pictures/company-logos/1/1.jpg',
    1,
    0,
    0,
    'Tampung Penyang Software House',
    '2018-09-18',
    'Tampung Penyang V Street',
    '+62 839-3833-3732',
    'tampung_penyang@software_house.com',
    '["https://fake-link.com/fake-account"]',
    'https://tampungpenyangsofwarehouse.wordpress.com',
    'Just Fake Company.',
    '["Conquer IT world.", "Conquer Atlantic Ocean.", "Another?"]',
    '["Buy more and more supercomputer.", "Add more and more RAM Capacity.", "Anything?"]',
    '["Consumers is Kings.", "Employers is Buttlers.", "Don&apos;t add more from this!"]',
    'Nothing.',
    'Come on, we are developing company.',
    'Nothing again.',
    '["And nothing again."]',
    '["NOTHING."]',
    1,
    '1970-01-01',
    '00:00:00',
    '1970-01-01',
    '00:00:00'
), (
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    CURRENT_DATE,
    CURRENT_TIME,
    CURRENT_DATE,
    CURRENT_TIME
);

INSERT INTO `job_vacancies` VALUES(
    NULL,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    1,
    CURRENT_DATE,
    CURRENT_TIME,
    CURRENT_DATE,
    CURRENT_TIME
);

INSERT INTO `job_requests` VALUES(
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT,
    1,
    1,
    CURRENT_DATE,
    CURRENT_TIME,
    CURRENT_DATE,
    CURRENT_TIME
);

INSERT INTO `job_submissions` VALUES(
    DEFAULT,
    1,
    1,
    CURRENT_DATE,
    CURRENT_TIME
);
